name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync deps (dev)
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest -q

      - name: Prepare SSH key
        if: ${{ secrets.SERVER_HOST && secrets.SERVER_USER && secrets.SSH_PRIVATE_KEY && secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Rsync project to server
        if: ${{ success() && secrets.SERVER_HOST && secrets.SERVER_USER && secrets.SSH_PRIVATE_KEY && secrets.SSH_KNOWN_HOSTS }}
        run: |
          RSYNC_RSH="ssh -i ~/.ssh/id_ci -o StrictHostKeyChecking=yes"
          DEST="${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/srv/apps/personal-website/app/"
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".venv" \
            --exclude "__pycache__" \
            ./ "$DEST"

      - name: Ensure uv on server and restart service
        if: ${{ success() && secrets.SERVER_HOST && secrets.SERVER_USER && secrets.SSH_PRIVATE_KEY && secrets.SSH_KNOWN_HOSTS }}
        run: |
          ssh -i ~/.ssh/id_ci ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            'export PATH="$HOME/.local/bin:$PATH"; \
             command -v uv >/dev/null 2>&1 || (curl -LsSf https://astral.sh/uv/install.sh | sh); \
             sudo systemctl restart personal-website && sudo systemctl status --no-pager personal-website || true'

